"""Regenerate native NFC and Unicode regex category tables.

Run with uv run --python 3.13 scripts/generate-unicode.py from the repository root.
The standard library unicodedata module supplies Unicode 15.1.0 data.
"""

import subprocess
import unicodedata

if unicodedata.unidata_version != "15.1.0":
    raise RuntimeError("Generation requires Unicode 15.1.0, supplied by Python 3.13")

whitespace = {
    9,
    10,
    11,
    12,
    13,
    32,
    133,
    160,
    5760,
    8232,
    8233,
    8239,
    8287,
    12288,
    *range(8192, 8203),
}


def category(codepoint):
    name = unicodedata.category(chr(codepoint))
    if name.startswith("L"):
        return "letter"
    if name.startswith("N"):
        return "number"
    if codepoint in whitespace:
        return "whitespace"
    return "other"


def decomposition(codepoint):
    text = unicodedata.decomposition(chr(codepoint))
    if not text or text.startswith("<"):
        return []
    return [int(part, 16) for part in text.split()]


ranges = []
combining = []
decompositions = []
compositions = []
previous = None
start = 0
for cp in range(0x110001):
    kind = category(cp) if cp < 0x110000 else "other"
    if kind != previous:
        if previous not in (None, "other"):
            ranges.append((start, cp - 1, previous))
        start = cp
        previous = kind
    if cp == 0x110000:
        break
    value = unicodedata.combining(chr(cp))
    if value:
        combining.append((cp, value))
    parts = decomposition(cp)
    if parts:
        decompositions.append((cp, parts[0], parts[1] if len(parts) > 1 else 0))
    if len(parts) == 2 and unicodedata.normalize("NFC", "".join(map(chr, parts))) == chr(cp):
        compositions.append((cp, parts[0], parts[1]))

# The tokenizer looks compositions up by their (first, second) pair.
compositions.sort(key=lambda entry: entry[1:])

with open("src/unicode_data.zig", "w") as output:
    output.write("//! Unicode 15.1.0 tables generated by scripts/generate-unicode.py.\n\n")
    output.write("pub const Category = enum { other, letter, number, whitespace };\n\n")
    output.write("/// Code points not covered by any range are `other`.\n")
    output.write("pub const Range = struct { first: u21, last: u21, category: Category };\n")
    output.write("pub const ranges = [_]Range{\n")
    for first, last, kind in ranges:
        output.write(f".{{ .first = {first}, .last = {last}, .category = .{kind} }},\n")
    output.write("};\n\n")
    output.write("pub const Combining = struct { codepoint: u21, class: u8 };\n")
    output.write("pub const combining = [_]Combining{\n")
    for cp, value in combining:
        output.write(f".{{ .codepoint = {cp}, .class = {value} }},\n")
    output.write("};\n\n")
    output.write("/// `second` is zero for single code point decompositions.\n")
    output.write("pub const Decomposition = struct { codepoint: u21, first: u21, second: u21 };\n")
    output.write("pub const decompositions = [_]Decomposition{\n")
    for cp, a, b in decompositions:
        output.write(f".{{ .codepoint = {cp}, .first = {a}, .second = {b} }},\n")
    output.write("};\n\n")
    output.write("/// Sorted by `first`, then `second`.\n")
    output.write("pub const compositions = [_]Decomposition{\n")
    for cp, a, b in compositions:
        output.write(f".{{ .codepoint = {cp}, .first = {a}, .second = {b} }},\n")
    output.write("};\n")

subprocess.run(["zig", "fmt", "src/unicode_data.zig"], check=True)
